numpy 語法模組
多維陣列操作 協助數據作圖 有功能函數庫

In [1]:
import numpy as np
# numpy array row 固定大小 從在同一組記憶體內的資料
array1 = np.array([[1, 2, 3],[4, 5, 6]])

print(array1)
array1

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

numpy 的性質

In [2]:
print(type(array1))  # 整體資料型態
print(array1.ndim)  # 資料維度(ex:array1有兩格)
print(array1.shape)  # 陣列的組成形狀(ex:2*3的矩陣[row*columu])
print(array1.size)  # 矩陣總共的格數
print(array1.dtype)  # 內容資料型態

<class 'numpy.ndarray'>
2
(2, 3)
6
int32


In [3]:
list1 = [1, 2, 3, 4]
list2 = [1, 2, 3, 4]
print(list1 + list2)
print(list1*3)

list3 = [[1, 2, 3, 4],[5, 6, 7, 8]]
print(type(list3))
print(type(list3[0]))
print(list3[0])
print(list3[1:3])

[1, 2, 3, 4, 1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
<class 'list'>
<class 'list'>
[1, 2, 3, 4]
[[5, 6, 7, 8]]


list 跟 array 的運算不同
list 僅可以做不同list之間的運算
array可以針對元素進行運算(element wise calculas)
且array運算後狀態不變

In [4]:
array1 = np.array([[1, 2, 3],[4, 5, 6]])

# element wise calculas 每個元素都進行運算
print(array1 + 2)
print(array1 - 2)
print(array1 * 2)
print(array1 / 2)
print()
print(array1 // 2)
print(array1 % 2)
print(array1 ** 2)

[[3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]

[[0 1 1]
 [2 2 3]]
[[1 0 1]
 [0 1 0]]
[[ 1  4  9]
 [16 25 36]]


In [5]:
array1 = np.array([[1, 2, 3],[4, 5, 6]])
array2 = np.array([[1, 3, 5],[2, 4, 6]])

# 對應的位置做運算
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print()
print(array1 % array2)
print(array1 // array2)
print(array1 ** array2)


[[ 2  5  8]
 [ 6  9 12]]
[[ 0 -1 -2]
 [ 2  1  0]]
[[ 1  6 15]
 [ 8 20 36]]
[[1.         0.66666667 0.6       ]
 [2.         1.25       1.        ]]

[[0 2 3]
 [0 1 0]]
[[1 0 0]
 [2 1 1]]
[[    1     8   243]
 [   16   625 46656]]


In [6]:
array1 = np.empty((2, 3))  # 創造一個2*3空np.array 數字會任意填入 格式為taple
print(array1)
array1 = np.zeros((2, 3))  # 印出一個內容是0的2*3 array
print(array1)
array1 = np.ones((2, 3))  # 印出一個內容是1的2*3 array
print(array1)
array1 = np.full((2, 3), 4.0)  # 全部填入4的 2*3 array
print(array1)
array1 = np.eye(3)  # 主對角線有3格 都填入1的方陣
print(array1)
array1 = np.diag([1, 2, 3])  # 主對角線填入1,2,3的方陣
print(array1)

[[1.         0.66666667 0.6       ]
 [2.         1.25       1.        ]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[4. 4. 4.]
 [4. 4. 4.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [7]:
# 一個範圍 可以放入0-9的值 使用上同range 但是arange可以放入非整數
print(np.arange(10))
print(np.arange(2, 10))
print(np.arange(2, 10, 3))  # 在2-10之間選出3個數字

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 5 8]


In [11]:
print(np.arange(2, 10.5, 0.5))
np.arange(6).reshape(2, 3)  # 重新排列矩陣 後面的矩陣總數要跟前面一樣

[ 2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5
  9.   9.5 10. ]


array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
array1 = np.linspace(0, 10, 5)  # 值的開頭跟結尾 要產生幾個值 且值的間隔會平均
print(array1)
print()
array2 = np.linspace(0, 10, 5, endpoint = False)  # 值的開頭跟結尾 要產生幾個值 最後一個值會去掉
print(array2)
print()
array3 = np.linspace(0, 10, 6)  # 值的開頭跟結尾 要產生幾個值 與上式不同
print(array3)

[ 0.   2.5  5.   7.5 10. ]

[0. 2. 4. 6. 8.]

[ 0.  2.  4.  6.  8. 10.]


In [22]:
# 範例
import numpy as np
a = np.array([6, 7, 8, 9])
b = np.arange(4)
c = a - b
print("a => ", a)
print("b => ", b)
print("c => ", c)
d = b ** 2
print("d => ", d)
print()
# 程式會進行比較 篩選出<=3的值 並列印出來(滿足條件的話會印出1)
f = np.array([5, -1, 3, 9, 0])
f[f<=3] = 1
print("f => ", f)

a =>  [6 7 8 9]
b =>  [0 1 2 3]
c =>  [6 6 6 6]
d =>  [0 1 4 9]

f =>  [5 1 1 9 1]


In [20]:
# 可篩選元素 選出 True 的位置
x = np.array([1, 2, 3])
y = np.array([True, False, True])
x[y]

array([1, 3])

In [23]:
array1 = np.arange(9).reshape(3, 3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
print(array1[1])  # 取出第 "2"row
print(array1[1][1:3])  # 取出第 "2"row的第1-2個
print(array1[1, 1:3])  # 取出第 "2"row的第1-2個
print(array1[:,2])  # 取出全部的 row 第"2"格的columu
print(array1[1, :])  # 取出第 "1"個 row  全部的columu 
print(array1[1:3, 0:2])  # 取出 row:1-2;columu:0-1

[3 4 5]
[4 5]
[4 5]
[2 5 8]
[3 4 5]
[[3 4]
 [6 7]]


In [31]:
import numpy as np
a = np.array([[1, 2, 3], [3, 6, 9], [2, 4, 6]])
print(a)
print()
print(a[1, 1:3])
print()
print(a[:, 1])
print()
# 將 row=1;columu=2 的數字置換成7
a[1, 2] = 7
print(a)
print()
# 將 每個row;columu=0的數字置換成[0, 9, 8]
a[:, 0]= [0, 9, 8]
print(a)

[[1 2 3]
 [3 6 9]
 [2 4 6]]

[6 9]

[2 6 4]

[[1 2 3]
 [3 6 7]
 [2 4 6]]

[[0 2 3]
 [9 6 7]
 [8 4 6]]


In [38]:
import numpy as np
a = np.array([[0, 1, 2, 3, 4, 5], 
              [10, 11, 12, 13, 14, 15], 
              [20, 21, 22, 23, 24, 25], 
              [30, 31, 32, 33, 34, 35], 
              [40, 41, 42, 43, 44, 45], 
              [50, 51, 52, 53, 54, 55]])
print()
print(a[(0, 1, 2, 3, 4), (1, 2, 3, 4, 5)])
print()
print(a[3:,[0, 2, 5]])  # row 從第 3 格開始 columu取0, 2, 5 格


[ 1 12 23 34 45]

[[30 32 35]
 [40 42 45]
 [50 52 55]]


In [67]:
array1 = np.arange(6)
array2 = array1.reshape(2, 3)
array3 = np.reshape(array1, (2, 3))
# 上述兩個操作皆相同 皆為改變array1的形狀 但是內容都是對準array1
print(array1)
print()
print(array2)
print()
array1[0] = 100  # 將第一格換成 100
print(array2)
print()
# 找出其記憶體位置
print(id(array1))
print(id(array2))
print(id(array1[0]))
print(id(array2[0, 0]))
# 由於arrya2、array3都是呼叫arrat1因此當array1改變時 2、3也會跟著改變
print()
print(array3)

[0 1 2 3 4 5]

[[0 1 2]
 [3 4 5]]

[[100   1   2]
 [  3   4   5]]

2530194283056
2530194280656
2530194395208
2530194395208

[[100   1   2]
 [  3   4   5]]


In [75]:
array1 = np.arange(6)
array1.resize(2, 3)
print(array1)
print()
# 這樣會創造出兩個不同的array1、array2
array2 = np.resize(array1, (3, 2))  # 複製出一組資料 稱為array2
print(array2)
print()
array1[0] = 100
print(array2)
print()
# 當array1改變時 array2並不會改變
print(array1)

[[0 1 2]
 [3 4 5]]

[[0 1]
 [2 3]
 [4 5]]

[[0 1]
 [2 3]
 [4 5]]

[[100 100 100]
 [  3   4   5]]


In [85]:
array1 = np.arange(8)
array2 = array1.reshape(2, 4)
array3 = np.resize(array1,(2, 4))
array4 = array1.resize(2, 4)  # 因為未定義出array1 因此使用resize呼叫會無效
print(array1)
print()
print(array2)
print()
print(array3)
print()
print(array4)
print()
print("Change")
print()
array1[0] = 100
print(array1)
print()
print(array2)
print()
print(array3)

[[0 1 2 3]
 [4 5 6 7]]

[[0 1 2 3]
 [4 5 6 7]]

[[0 1 2 3]
 [4 5 6 7]]

None

Change

[[100 100 100 100]
 [  4   5   6   7]]

[[100 100 100 100]
 [  4   5   6   7]]

[[0 1 2 3]
 [4 5 6 7]]


In [87]:
array1 = np.arange(6)
array1.resize(2, 3)
print(array1)
print()
# 如果使用resize 當字串不足時會自動重複
array2 = np.resize(array1, (3, 3))
print(array2)

[[0 1 2]
 [3 4 5]]

[[0 1 2]
 [3 4 5]
 [0 1 2]]


In [90]:
import numpy as np
# 程式只要row有符合 會自動變化成可運算之符號
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([10, 10, 10])
c = a + b
print(c)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
